[program:gromox-istore]
command=/usr/libexec/gromox/istore
autostart=false
autorestart=true
stdout_logfile=/var/log/supervisor-gromox-istore.log
stderr_logfile=/var/log/supervisor-gromox-istore-err.log
